name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install GDAL system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gdal-bin libgdal-dev

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Configure GDAL environment variables
      run: |
        echo "export CPLUS_INCLUDE_PATH=/usr/include/gdal" >> $GITHUB_ENV
        echo "export C_INCLUDE_PATH=/usr/include/gdal" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: poetry install

    - name: Build docs
      run: poetry run mkdocs build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        force_orphan: true
